apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-deployment-master
  labels:
    app:  kubernetes-app-master
spec:
  replicas: 4
  selector:
    matchLabels: 
      app: kubernetes-app-master
  template:
    metadata:
      labels:
        app: kubernetes-app-master
    spec:
      containers:
      - name: kubernetes-app-master
        image: rohit2522/nagp-jenkins-assignment:master-latest
        ports: 
        - containerPort: 8080
        imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: kubernetes-service-master
spec:
  selector:
    app: kubernetes-app-master
  ports:
  - nodePort: 30157
    port: 8080
    targetPort: 8080
  type: NodePort



